Repository w3c/dxwg, pull requests merged in 2019-11, with the labels that each got.

#1147 Added Appendix for DCAT example
  conneg-by-ap/index.html
Labels: profile-negotiation

#1157 Changes to make respec show correct links
  dcat/config.js
Labels: dcat, editorial

#1132 Conneg editorial
  README.md
  connegp/altr.svg
  connegp/altr.ttl
  connegp/config.js
  connegp/extra.css
  connegp/index.html
  connegp/profiles-hierarchy.svg
  connegp/profiles.ttl
Labels: editorial, profile-negotiation

#1162 Tweaks to handle #1149 - remove MUST ref to HTTP
  connegp/index.html
Labels: profile-negotiation

#1164 Conneg 3 pwd docchecks editorial
  connegp/config.js
  connegp/extra.css
  connegp/index.html
Labels: editorial, profile-negotiation

#1166 Conneg self canonical
  connegp/index.html
Labels: profile-negotiation

#1165 Conneg 3 pwd editorial
  connegp/index.html
  connegp/profiles.ttl
Labels: editorial, profile-negotiation

#1168 DCAT remove at risk notes
  dcat/index.html
Labels: dcat

#1167 Conneg Implementation Report
  connegp-implementation-report/config.js
  connegp-implementation-report/extra.css
  connegp-implementation-report/index.html
Labels: implementation-evidence, profile-negotiation

#1163 Add ref to #505 - order or precedence and remove MUST
  connegp/config.js
  connegp/index.html
Labels: profile-negotiation

#1171 small into wording change for FP naming consistency
  connegp/index.html
Labels: profile-negotiation

#1172 Removed companyURL for Lars
  connegp/config.js
Labels: editorial, profile-negotiation

#1173 updating affiliation to include previous one
  dcat-implementation-report/config.js
  dcat/config.js
Labels: dcat

#1180 Prof 3 pwd editorial
  prof/config.js
  prof/index.html
  prof/rdf/prof.rdf
  prof/rdf/prof.ttl
  prof/rdf/profile.ttl
Labels: editorial, profiles-vocabulary

#1179 Prof 3 pwd issues
  connegp/config.js
  prof/index.html
  prof/rdf/prof.ttl
  prof/roles/resource_roles.ttl
Labels: profiles-vocabulary
