Repository w3c/dxwg, pull requests merged in 2019-09, with the labels that each got.

#1039 Conneg redefs
  .gitignore
  conneg-by-ap/config.js
  conneg-by-ap/extra.css
  conneg-by-ap/index.html
  conneg-by-ap/orcid_logo.png
Labels: profile-negotiation

#1036 Conneg editorial
  conneg-by-ap/config.js
  conneg-by-ap/index.html
Labels: profile-negotiation

#1037 Conneg action 356
  conneg-by-ap/index.html
Labels: profile-negotiation

#1030 Conneg profiles appendix
  conneg-by-ap/index.html
  conneg-by-ap/profile-hierarchy.svg
  conneg-by-ap/profiles-hierarchy.svg
  conneg-by-ap/profiles.ttl
Labels: profile-negotiation

#1015 Prof definitions
  profilesont/config.js
  profilesont/index.html
Labels: ON HOLD profiles-vocabulary

#1046 conformstTo isolated example
  profilesont/index.html
Labels: ON HOLD profiles-vocabulary

#1050 Conneg 3 pwd candidate
  .gitignore
  conneg-by-ap/config.js
  conneg-by-ap/extra.css
  conneg-by-ap/index.html
  conneg-by-ap/profiles.ttl
  profilesont/index.html
Labels: editorial, profile-negotiation

#1001 Links to ISO-19115-1...
  dcat/index.html
Labels: dcat, feedback

#1028 Address link checker reports
  dcat/index.html
Labels: dcat, editorial

#1035 Italian translation starting from pr1034
  dcat/rdf/dcat.ttl
Labels: dcat, editorial

#1034 dcat-issue-983 - comments -> definitions
  dcat/rdf/dcat.ttl
Labels: dcat, editorial

#1056 DCAT Stranded comments
  dcat/index.html
Labels: dcat, editorial, feedback

#1058 Addressing issue #1057 - move external terms into separate RDF graph
  dcat/rdf/dcat-external.ttl
  dcat/rdf/dcat.ttl
Labels: dcat, editorial

#1038 Conneg altprofiles model
  conneg-by-ap/altr.svg
  conneg-by-ap/altr.ttl
  conneg-by-ap/index.html
Labels: profile-negotiation

#1060 Assesment of token positions
  conneg-by-ap/index.html
Labels: profile-negotiation

#1063 Indicate tokens through separate Link header
  conneg-by-ap/index.html
Labels: change-proposal, content-negotiation, identification, profile-negotiation

#1066 Added specification of Link attribute token
  conneg-by-ap/index.html
Labels: profile-negotiation

#1011 Addressing issue #1013 - Some minor editorial nits in DCAT
  dcat/index.html
Labels: dcat, editorial

#1052 DCAT: Further updates to ack section
  dcat/config.js
  dcat/index.html
Labels: critical, dcat, editorial

#1067 Fixes for the issues in #1066
  conneg-by-ap/index.html
Labels: profile-negotiation

#1075 Updated section "Token mappings"
  conneg-by-ap/index.html
Labels: profile-negotiation

#1076 Marked http implementation as at-risk
  conneg-by-ap/index.html
Labels: profile-negotiation

#1077 Updated Changes section
  conneg-by-ap/index.html
Labels: editorial, profile-negotiation

#1080 Conneg link sec fix
  conneg-by-ap/index.html
Labels: editorial, profile-negotiation

#1079 changes section tidy
  conneg-by-ap/index.html
Labels: editorial, profile-negotiation

#1081 DCAT: Updates to ack section
  dcat/index.html
Labels: critical, dcat, editorial

#1082 Added back specification of attribute "token"
  conneg-by-ap/index.html
Labels: editorial, profile-negotiation

#1074 Editorial fixes for Prof 3 pwd candidate prior to introducing final substantive change proposals.
  README.md
  prof/.gitignore
  prof/alignments/adms.svg
  prof/alignments/adms.ttl
  prof/alignments/dcat.svg
  prof/alignments/dcat.ttl
  prof/alignments/dct.svg
  prof/alignments/dct.ttl
  prof/alignments/owl.svg
  prof/alignments/owl.ttl
  prof/alignments/skos.svg
  prof/alignments/skos.ttl
  prof/alignments/voaf.svg
  prof/alignments/voaf.ttl
  prof/config.js
  prof/examples/adms.svg
  prof/examples/adms.ttl
  prof/examples/csiro-dummy-dcap.svg
  prof/examples/csiro-dummy-dcap.ttl
  prof/examples/dcat-ap.svg
  prof/examples/dcat-ap.ttl
  prof/examples/dcat.svg
  prof/examples/dcat.ttl
  prof/examples/ga.svg
  prof/examples/ga.ttl
  prof/examples/hierarchy.svg
  prof/examples/ogc.ttl
  prof/examples/pav.ttl
  prof/figures/broaderTransitive.jpg
  prof/figures/element-key.svg
  prof/figures/initial.svg
  prof/figures/isInheritedFrom.svg
  prof/figures/isTransitiveProfileOf.svg
  prof/figures/prof.svg
  prof/index.html
  prof/ns.html
  prof/rdf/constraints.ttl
  prof/rdf/prof.rdf
  prof/rdf/prof.ttl
  prof/rdf/profile.ttl
  prof/rdf/validation.ttl
  prof/roles/config-roles.js
  prof/roles/resource_roles.html
  prof/roles/resource_roles.svg
  prof/roles/resource_roles.ttl
  prof/style/style.css
  profilesont/README.md
  profilesont/examples/adms.svg
  profilesont/examples/csiro-dummy-dcap.svg
  profilesont/examples/dcat-ap.svg
  profilesont/examples/dcat.svg
  profilesont/examples/epub.svg
  profilesont/examples/ga.svg
  profilesont/examples/hierarchy.svg
  profilesont/figures/initial.svg
  profilesont/figures/isInheritedFrom.svg
  profilesont/figures/isTransitiveProfileOf.svg
  profilesont/figures/profilesont.svg
  profilesont/style/orcid_logo.png
Labels: profiles-vocabulary

#1083 Added order of precedence text
  conneg-by-ap/index.html
Labels: content-negotiation, profile-negotiation

#1087 Status of doc updated
  dcat/config.js
  dcat/index.html
Labels: dcat, editorial

#1062 Dcat - RDF examples in TTL and JSON-LD
  dcat/examples/basic-example.jsonld
  dcat/examples/basic-example.ttl
  dcat/examples/catalog-record.jsonld
  dcat/examples/catalog-record.ttl
  dcat/examples/classifying-thematically.jsonld
  dcat/examples/classifying-thematically.ttl
  dcat/examples/classifying-types.jsonld
  dcat/examples/classifying-types.ttl
  dcat/examples/conformance-standards.jsonld
  dcat/examples/conformance-standards.trig
  dcat/examples/dataset-002.jsonld
  dcat/examples/dataset-002.ttl
  dcat/examples/dataset-003.jsonld
  dcat/examples/dataset-003.ttl
  dcat/examples/genoa-busstop.jsonld
  dcat/examples/genoa-busstop.ttl
  dcat/examples/identifier-types.jsonld
  dcat/examples/identifier-types.ttl
  dcat/examples/spatial-properties.jsonld
  dcat/examples/spatial-properties.ttl
  dcat/examples/temporal-properties.jsonld
  dcat/examples/temporal-properties.ttl
  dcat/index.html
  dcat/rdf/dcat-external.jsonld
  dcat/rdf/dcat-external.rdf
  dcat/rdf/dcat.jsonld
  dcat/rdf/dcat.rdf
Labels: dcat

#1092 Add "recommended"
  dcat/index.html
Labels: dcat, editorial

#1096 Conneg urn delimiters
  conneg-by-ap/index.html
Labels: profile-negotiation

#1095 Conneg data profile
  conneg-by-ap/index.html
Labels: profile-negotiation

#1090 Issue 1088 - PROF ref to B2 & 6 x typo errors fixed
  conneg-by-ap/index.html
Labels: editorial, profile-negotiation

#1094 editorial change: referring to dcat vocabulary specification
  dcat/index.html
Labels: dcat, editorial

#1098 revising point 3 of section rdf representation
  dcat/index.html
Labels: dcat, editorial

#1097 Added definition for functional specification
  conneg-by-ap/index.html
Labels: profile-negotiation

#1101 Editorial changes from Antoine and Riccardo
  conneg-by-ap/index.html
Labels: editorial, profile-negotiation

#1099 Conneg qsa delimeter
  conneg-by-ap/index.html
Labels: profile-negotiation

#1103 changes as per Issue 544
  conneg-by-ap/index.html
Labels: profile-negotiation
